### ISSUE TITLE
Ls Prefix

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#108]
```bash
curl -X 'GET' \
  'http://nichujie.xyz/api/v1/domains/test/problems/commit-test/config/ls?amount=100' \
  -H 'accept: application/json'
```
Gives all files under `Cases/`, not root directory.

LakeFS: http://nichujie.xyz:34766/repositories/joj-config-3b948e3a-64ec-45d0-b0dd-2e7b3acb2be7/objects?ref=problem-07d7aa99-024b-4017-8ec1-30a5ad3b2b09

**Comment by BoYanZh** [comment]
You need `delimiter=%2F`
