### ISSUE TITLE
User Search API

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#57]
Need an API for searching users:
* Search by username
* Search bu studentId
* Search by email (optional, useful for normal use cases)
* **limit result to 5, do not support pagination**
<img width="50%" src="https://user-images.githubusercontent.com/17191827/142067523-39f00a9b-b5ec-4384-9597-8d30d71d0d15.png"/>

**Comment by tc-imba** [comment]
We can add some filters in find domain users

**Comment by tc-imba** [comment]
We added two endpoints in #61:

+ GET /api/v1/users for site admin to view all users. This API do not have any restriction on search query and pagination
+ GET /api/v1/domains/{domain}/candidates for domain admin to search candidates. This API have a hard pagination limit that only the first 10 results are shown, the length search query must also be at least 2.
