### ISSUE TITLE
List Problem in Problem Set

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#65]
List problem in problem set:
* problem basic info with submission info (last submission/submission status)

Note: `/domains/{domain}/problems` is a bit different with the above API: submission info is a super set of the above one

![image](https://user-images.githubusercontent.com/17191827/142743322-a717d35c-7001-47ea-aac0-99e285a38075.png)

**Comment by tc-imba** [comment]
only in list or in both list and get?

**Comment by nichujie** [comment]
我找到了，problems在get problem set里。
![image](https://user-images.githubusercontent.com/17191827/142941249-01bc22d4-aec1-4b1b-bcb0-9559cbd69bcc.png)
不过还有一个问题在于获取problem set里problems的时候要顺便知道用户最后一次record的状态。
不知道这个怎么做会好一点，join会很慢吗？

**Comment by nichujie** [comment]
![image](https://user-images.githubusercontent.com/17191827/142941724-74f3da72-0371-4630-b63e-22c29ae7e464.png)
顺便list problems也有这个需求，可以顺便看掉

**Comment by tc-imba** [comment]
只需要显示state就可以了？

**Comment by nichujie** [comment]
对的，最简单的话一个state和一个record id就行
