### ISSUE TITLE
remove content field in list problems

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#72]

**Comment by nichujie** [comment]
顺便增加最近一次的提交状态（AC，WA，TLE，MLE...）

**Comment by tc-imba** [comment]
现在record状态只有
+ accepted  通过
+ rejected 结果错误 (WA，TLE，MLE)
+ failed 评测机错误

因为一个record的每个case错误都能不一样，我们是否需要按照某种优先级总结一个错误出来？

**Comment by tc-imba** [comment]
content removed in 0a3cc7726520cdfb0f5a4ab2a25cc36861893e87

**Comment by nichujie** [comment]
list problem里也要拿掉content @tc-imba 

list接口一般不传很大的字段

**Comment by tc-imba** [comment]
fixed in 5c80f1d86083da13dd0256715932b7143c551c5b
