### ISSUE TITLE
Update Domain User

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#74]
## 正常update时出现InternalError

详见: https://rollbar.com/sjtu/horse/items/24/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification

## 无法update成标准role以外的角色

![image](https://user-images.githubusercontent.com/17191827/144769472-3d94275f-e3d6-4088-9fc6-5af600d6126c.png)

如图创建一个自定义role，出现下图错误：

![image](https://user-images.githubusercontent.com/17191827/144769512-bfcf9ea4-1f1c-45c7-b570-070e601b5b14.png)

**Comment by tc-imba** [comment]
fixed in bacbc9ace2ddaac893ff0d239a186d494859e232
