### ISSUE TITLE
Search Domain Tags

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#75]
![image](https://user-images.githubusercontent.com/17191827/145681812-db671357-13f4-4082-b4b5-4eb425d22f07.png)

需要一个搜索当前已存Tag的API，类似searchCandidate.
* 不需要分页
* 一次性显示所有
* 前端做search

**Comment by nichujie** [comment]
理论上返回个string array就可以了

**Comment by nichujie** [comment]
最好list domains再支持下按照tag筛选

**Comment by BoYanZh** [comment]
4e88176e, 16548416
