### ISSUE TITLE
Update Problem Config By Archive

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#76]
![image](https://user-images.githubusercontent.com/17191827/145694836-24195a81-57c1-42bc-bb3e-aa44b4c908dd.png)

上传成功后显示ProblemConfigNotFound，数据库无数据。

---

P.S. 需要一个接口知道problem是否已经有了config，类似效果：
![image](https://user-images.githubusercontent.com/17191827/145694904-2784d8fe-2946-4fb8-b83a-3ef7c3bdc137.png)

* 可以在get problem里返回
* 或者problemConfig组里新建一个api用来干这个事

**Comment by tc-imba** [comment]
这个是因为没有调用 /config/commit 进行commit
这玩意设计是在commit前可以随便修改的

**Comment by nichujie** [comment]
![image](https://user-images.githubusercontent.com/17191827/147154244-936c008f-a374-43c7-a1c9-c54981f475c8.png)

![image](https://user-images.githubusercontent.com/17191827/147154229-46526aac-ea42-4f19-b1ef-c75a67583e57.png)

有些许奇怪，是不是什么代码忘删了？

顺便Problem是不是应该有个languages字段

**Comment by nichujie** [comment]
> 这个是因为没有调用 /config/commit 进行commit 这玩意设计是在commit前可以随便修改的
> 
> 是否要加一个auto_commit: bool

不用加，把commit修好就行，保持统一

**Comment by tc-imba** [comment]
应该是可以传一个commit message的吧？
