### ISSUE TITLE
GET ProblemSet return last record time

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/horse#78]
<img width="50%" src="https://user-images.githubusercontent.com/17191827/146258668-c5cc12ea-4ef4-4fa7-82c7-6a33dadfcc8c.png" />

每个problem的record顺便返回下提交时间，用于：

![image](https://user-images.githubusercontent.com/17191827/146259180-f3ab63b0-4e32-4cf9-a713-dfb31fceaf71.png)

**Comment by nichujie** [comment]
追加：list record

**Comment by tc-imba** [comment]
fixed in 5c80f1d86083da13dd0256715932b7143c551c5b
